let a=3;
let b=a++;
console.log("b=",b=a++);
b=a--;
console.log("b=",b=a--);
console.log("== :",a==3);
console.log("!=:",a!=4);
console.log("===",a===3);
console.log("!==",a!=='4');
console.log(">",a>7);
console.log("<",a<2);
console.log("a>=",a>=7);
console.log("<=",a<=4);